global:
  scrape_interval:     60s
  evaluation_interval: 60s

rule_files:
  - "node_rules.yml" 

scrape_configs:

  - job_name: node
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          instance: localhost

