#基础配置
base:
  port: 9680
  #数据库类型 mysql,postgresql,opengauss,kingbase,clickhouse,sqlite,dm(达梦)
  dbtype: mysql
  #缓存类型 gcache,redis(暂未使用)
  cachetype: gcache
log:
  # std|file
  output: std
  # trace|debug|info|warn
  level: info
  # 是否打印调用者信息
  caller: true
  # 日志目录
  dir: ./log
#数据库配置
database:
  host: 192.168.8.206
  username: root
  password: root123456
  dbname: ha
  port: 32321
  minconns: 150
  maxconns: 200
slave:
  host: 192.168.8.206
  username: root
  password: root123456
  dbname: alert
  port: 32321
  minconns: 160
  maxconns: 200
#storepath: ./upload/file
backend:
  url: http://192.168.8.122:8100
